name: CI

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/ci.yml'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon.dist'
      - 'pint.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Code Style (Pint)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Run Pint
        run: ./vendor/bin/pint --test

  phpstan:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Static Analysis (PHPStan)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github

  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.3]
        laravel: [^12.0, ^11.31]
        stability: [prefer-stable]
        include:
          - laravel: ^12.0
            testbench: ^10.0
          - laravel: ^11.31
            testbench: ^9.0
          # Test prefer-lowest only on oldest combination
          - php: 8.3
            laravel: ^11.31
            testbench: ^9.0
            stability: prefer-lowest
            os: ubuntu-latest

    name: Tests P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        if: ${{ !env.ACT }}
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        if: ${{ !env.ACT }}
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci
